[theme]
base = "light"
primaryColor = "#e4f222"
backgroundColor = "#f4f5f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#141d2c"
font = "Inter, sans-serif"
baseFontWeight = 400

[[theme.fontFaces]]
family = "Inter"
url = "app/static/fonts/Inter-Regular.woff2"
weight = "400"
style = "normal"

[browser]
gatherUsageStats = false

[server]
headless = true
enableStaticServing = true
